#!/usr/bin/env lua

local function exit(...)
  io.stderr:write(string.format(...))
  io.stderr:write("\n")
  os.exit(1)
end

local function tryrequire(mod)
  local s, result = pcall(require, mod)
  if not s then exit(result) end
  return result
end

if not os.getenv("HOME") then
  exit("$HOME not set - are you on windows?")
end

if not arg then
  exit("'arg' table is not present; you need at least Lua 5.3")
end

local dir = os.getenv("HOME") .. "/.piecestopractice/"
local days = dir .. "days/"
local assignments = dir .. "assignments/"

local stat = tryrequire("posix.sys.stat")
local dirent = tryrequire("posix.dirent")

local actions = {}

actions.help = function()
  io.stderr:write([[
Usage: ptp <command> [arg ...]

A fairly simple command-line music practice tool.  Available commands:

help:
  prints this help message

add-assignment <longname>:
  add the specified assignment to the program's data directory; prints the ID of the new assignment

add-set <set>:
  create a new practice set

practice <name>:
  mark the specified assignment as practiced for the day, or add time to it

list <set> [qualifier]:
  return all assignment in the specified list: all, practiced, sets, or the name of a set; if 'practiced', qualifier can be a day to list

add-to-set <name> <set>:
  add the specified assignment to the specified set

del-from-set <name> <set>:
  remove the specified assignment from the specified set

get-streak
  print the number of days in a row you've marked something

Pieces to Practice is copyright (c) 2022 Ocawesome101 under the GNU GPLv3.
]])
  os.exit(0)
end

local function checkdirs()
  stat.mkdir(dir)
  stat.mkdir(days)
  stat.mkdir(assignments)
end

local function date(time)
  return os.date("%Y-%m-%d", time)
end

actions["add-assignment"] = function(longname)
  if not longname then exit("missing longname; see '%s help'", arg[0]) end
  checkdirs()
  math.randomseed(os.time())
  local name = tostring(math.random(100000, 999999))
  local f, err = io.open(assignments .. name, "w")
  if not f then exit("failed opening file: %s", err) end
  f:write(longname)
  f:close()
  print(name)
end

actions["add-set"] = function(set)
  if not set then exit("missing set; see '%s help'", arg[0]) end
  checkdirs()
  local s = stat.lstat(assignments .. set)
  if s then exit("there is already a set or assignment by that name") end
  stat.mkdir(assignments .. set)
end

actions["practice"] = function(name)
  if not name then exit("missing name; see '%s help'", arg[0]) end
  checkdirs()
  local day = days .. date()
  local assignment = day .. "/" .. name
  stat.mkdir(day)
  local time = 0
  local score = 0

  if stat.lstat(assignment) then
    local hand = io.open(assignment, "r")
    time = tonumber(hand:read("l")) or 0
    score = tonumber(hand:read("l")) or 0
  end

  local start = os.time()
  io.write("when done, enter a score and press ENTER\n")
  score = math.max(0, math.min(tonumber(io.read("l")) or 5, 10))
  time = time + os.time() - start

  local hand = io.open(assignment, "w")
  hand:write(tostring(time), "\n")
  hand:write(tostring(score), "\n")
  hand:close()
end

actions["list"] = function(set, qualifier)
  if not set then exit("missing 'set' argument; see '%s help'", arg[0]) end
  if qualifier and set ~= "practiced" then
    exit("misguided 'qualifier' argument; see '%s help'", arg[0])
  end
  checkdirs()
  if set == "all" then
    for file in dirent.files(assignments) do
      local full = assignments .. file
      if file ~= "." and file ~= ".." and stat.lstat(full).st_mode & 0xFFFF
          ~= stat.S_IFDIR then
        local hand = io.open(full, "r")
        local data = hand:read("a")
        hand:close()
        print(file, data)
      end
    end
  elseif set == "sets" then
    for file in dirent.files(assignments) do
      local full = assignments .. file
      if file ~= "." and file ~= ".." and stat.lstat(full).st_mode & 0xFFFF
          == stat.S_IFDIR then
        print(file)
      end
    end
  elseif set == "days" then
    for file in dirent.files(days) do
      if file ~= "." and file ~= ".." then
        print(file)
      end
    end
  elseif set == "practiced" then
    qualifier = qualifier or date()
    local day = days .. qualifier
    for file in dirent.files(day) do
      local full = assignments .. file
      if file ~= "." and file ~= ".." then
        local hand = io.open(full, "r")
        if not hand then
          io.stderr:write("bad assignment id %d - removing it\n")
          os.remove(full)
        else
          local data = hand:read("a")
          hand:close()
          print(file, data)
        end
      end
    end
  else
    exit("invalid 'set' argument; see '%s help'", arg[0])
  end
end

actions["add-to-set"] = function(name, set)
  if not name then exit("missing 'name' argument; see '%s help'", arg[0]) end
  if not set then exit("missing 'set' argument; see '%s help'", arg[0]) end

  local full = assignments .. set .. "/" .. name
  local h = io.open(full, "w")
  if not h then exit("given practice set is not present") end
  h:close()
end

actions["del-from-set"] = function(name, set)
  local full = assignments .. set .. "/" .. name
  os.remove(full)
end

actions["get-streak"] = function()
  local time = os.time()
  local count = -1
  repeat
    local day = date(time)
    time = time - 86400 -- remove one day
    count = count + 1
  until not stat.lstat(days .. day)
  print(count)
end

local command = arg[1]
if not command then
  exit("see '%s help' for usage", arg[0])
elseif not actions[command] then
  exit("subcommand '%s' is not available; see '%s help'", command, arg[0])
else
  actions[command](table.unpack(arg, 2))
end
