#!/usr/bin/env lua

local id = tonumber(io.read():match("id=(%d+)"))
local start = tonumber(io.read():match("start=(%d+)"))
local rating = tonumber(io.read():match("rating=(%d+)"))

os.execute(string.format("./ptp practice %d %d %d", id, start, rating))

print([[
<meta http-equiv="refresh" content="1; URL=/">
<link rel="stylesheet" href="https://ulos.pickardayune.com/ulos/style.css">
Completed.
]])
