#!/usr/bin/env lua

local assignments = ""
local practiced = ""
local sets = "<option onclick='window.location=\"/?set=all\"'>all</option>"
local blacklist = {}

local lset = (io.read("l") or ""):match("set=(.+)")

local ptp = io.popen("./ptp list practiced")

for assignment in ptp:lines("l") do
  local id, name = assignment:match("^(%d+) *(.+)$")
  blacklist[id] = true
  practiced = practiced .. string.format("<a href='/practice?id=%s'>%s</a> | <a href='/remove?id=%s'>Remove</a><br>\n",
      id, name, id)
end

ptp:close()

ptp = io.popen("./ptp list " .. (lset or "all"), "r")

for assignment in ptp:lines("l") do
  local id, name = assignment:match("^(%d+) *(.+)$")
  if not blacklist[id] then
    assignments = assignments .. string.format("<a href='/practice?id=%s'>%s</a> | <a href='/remove?id=%s'>Remove</a><br>\n",
      id, name, id)
  end
end

ptp:close()

ptp = io.popen("./ptp list sets", "r")

for set in ptp:lines("l") do
  sets = sets .. string.format("<option onclick='window.location=\"/?set=%s\"'%s>%s</option>", set, set == lset and " selected" or "", set)
end

ptp:close()

ptp = io.popen("./ptp get-streak", "r")
local streak = tonumber(ptp:read("a"))
ptp:close()

print(string.format([[
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="https://ulos.pickardayune.com/ulos/style.css">

<html>
  <body>
    <p class="brightwhite">Pieces to Practice<br>------------------</p>
    <p>Practice streak: <span class="brightwhite">%d</span></p>
    <p>Current set:
      <select id="set" name="set" required="required">%s</select>
    </p>
    <p>Set Contents <a href="/add-assignment?set=%s">Add</a><br>
       ------------</p>
    <p>%s</p>
    <p>Practiced assignments<br>
       ---------------------</p>
    <p>Fields, in order: Name, Time, Rating<br>
    Assignments are not sorted.<br>
    %s</p>
    <p>---------------------<br><a href="/about">About</a></p>
  </body>
</html>
]], streak or 0, sets, lset or "all", assignments or "", practiced or ""))
