#!/usr/bin/env lua

local assignments = ""
local practiced = ""
local blacklist = {}
local ptp = io.popen("./ptp list practiced")

for assignment in ptp:lines("l") do
  local id, name = assignment:match("^(%d+) *(.+)$")
  blacklist[id] = true
  practiced = practiced .. string.format(
    "<a href='/practice?id=%s'>%s</a><br>\n", id, name)
end

ptp:close()

ptp = io.popen("./ptp list all", "r")

for assignment in ptp:lines("l") do
  local id, name = assignment:match("^(%d+) *(.+)$")
  if not blacklist[id] then
    assignments = assignments .. string.format(
      "<a href='/practice?id=%s'>%s</a><br>\n", id, name)
  end
end

ptp:close()

ptp = io.popen("./ptp get-streak", "r")
local streak = tonumber(ptp:read("a"))
ptp:close()

print(string.format([[
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="stylesheet" href="https://ulos.pickardayune.com/ulos/style.css">

<html>
  <body>
    <p class="brightwhite">Pieces to Practice<br>------------------</p>
    <p>Practice streak: <span class="brightwhite">%d</span></p>
    <p>Current assignments <a href="/add-assignment">Add</a><br>
       -------------------</p>
    <p>%s</p>
    <p>Practiced assignments<br>
       ---------------------</p>
    <p>Fields, in order: Name, Time, Rating<br>
    Assignments are not sorted.<br>
    %s</p>
  </body>
</html>
]], streak or 0, assignments or "", practiced or ""))
